steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/github.com/ciboulette/cloud-run-test:$SHORT_SHA",
        ".",
      ]
    # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/github.com/ciboulette/cloud-run-test:$SHORT_SHA",
      ]
    # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "cloud-run-test",
        "--image",
        "gcr.io/$PROJECT_ID/github.com/ciboulette/cloud-run-test:$SHORT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
images: ["gcr.io/$PROJECT_ID/github.com/ciboulette/cloud-run-test:$SHORT_SHA"]
